spring:
  application:
    name: Chatter

  datasource:
    url: jdbc:mysql://localhost:3307/chatter
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migration: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090/realms/chatter
          jwk-set-uri: http://127.0.0.1:9090/realms/chatter/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload:
    dir: uploads

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG